table fct_transfer_market_value_analysis

	/// Distinct transfer records in the active filter context.
	measure 'Transfer Count' = DISTINCTCOUNT(fct_transfer_market_value_analysis[transfer_key])
		formatString: #,0 "transfer"
		displayFolder: Market Value Analysis\01 Scope

	/// Transfers with a known transfer fee.
	measure 'Known Fee Transfer Count' = CALCULATE([Transfer Count], fct_transfer_market_value_analysis[has_known_transfer_fee] = TRUE())
		formatString: #,0 "transfer"
		displayFolder: Market Value Analysis\01 Scope

	/// Share of transfer records with a known transfer fee.
	measure 'Known Fee Coverage %' = COALESCE(DIVIDE([Known Fee Transfer Count], [Transfer Count]), 0)
		formatString: 0.0%
		displayFolder: Market Value Analysis\02 Data Trust

	/// Average transfer fee, excluding unknown fee records.
	measure 'Average Known Transfer Fee' = CALCULATE(AVERAGE(fct_transfer_market_value_analysis[transfer_fee]), fct_transfer_market_value_analysis[has_known_transfer_fee] = TRUE())
		formatString: €0.0
		displayFolder: Market Value Analysis\03 Commercial Value

	/// Total known transfer fee in the active filter context.
	measure 'Total Known Transfer Fee' = CALCULATE(SUM(fct_transfer_market_value_analysis[transfer_fee]), fct_transfer_market_value_analysis[has_known_transfer_fee] = TRUE())
		formatString: €0.0
		displayFolder: Market Value Analysis\03 Commercial Value

	/// Transfers with both a known fee and a market-value baseline.
	measure 'Comparable Transfer Count' = CALCULATE([Transfer Count], fct_transfer_market_value_analysis[has_fee_market_value_comparison] = TRUE())
		formatString: #,0 "transfer"
		displayFolder: Market Value Analysis\02 Data Trust

	/// Share of transfer records eligible for fee versus market-value comparison.
	measure 'Comparison Coverage %' = DIVIDE([Comparable Transfer Count], [Transfer Count])
		formatString: 0.0%
		displayFolder: Market Value Analysis\02 Data Trust

	/// Average fee premium or discount versus the market-value baseline.
	measure 'Average Fee Premium Discount %' = DIVIDE(CALCULATE(AVERAGE(fct_transfer_market_value_analysis[fee_market_value_difference_pct]), fct_transfer_market_value_analysis[has_fee_market_value_comparison] = TRUE()), 100)
		formatString: 0.0%
		displayFolder: Market Value Analysis\03 Commercial Value

	/// Transfers with an observable post-transfer market-value outcome.
	measure 'Post Transfer Outcome Count' = CALCULATE([Transfer Count], fct_transfer_market_value_analysis[has_post_transfer_value_change] = TRUE())
		formatString: #,0 "transfer"
		displayFolder: Market Value Analysis\02 Data Trust

	/// Share of transfers with an observable post-transfer value outcome.
	measure 'Post Transfer Outcome Coverage %' = COALESCE(DIVIDE([Post Transfer Outcome Count], [Transfer Count]), 0)
		formatString: 0.0%
		displayFolder: Market Value Analysis\02 Data Trust

	/// Average post-transfer market-value change for observable outcomes.
	measure 'Average Post Transfer Value Change %' = DIVIDE(CALCULATE(AVERAGE(fct_transfer_market_value_analysis[market_value_change_after_transfer_pct]), fct_transfer_market_value_analysis[has_post_transfer_value_change] = TRUE()), 100)
		formatString: 0.0%
		displayFolder: Market Value Analysis\04 Outcomes

	/// Share of observable transfer outcomes with a market-value increase.
	measure 'Value Increase Rate %' = COALESCE(DIVIDE(CALCULATE([Transfer Count], fct_transfer_market_value_analysis[market_value_direction_after_transfer] = "increase"), [Post Transfer Outcome Count]), 0)
		formatString: 0.0%
		displayFolder: Market Value Analysis\04 Outcomes

	/// Selected player label for drill-through pages.
	measure 'Selected Transfer Player' = SELECTEDVALUE(fct_transfer_market_value_analysis[player_name], "Oyuncu secilmedi")
		displayFolder: Market Value Analysis\05 Dynamic Context

	/// Dynamic context summary driven by active filters.
	measure 'Transfer Context Summary' = VAR SeasonLabel = SELECTEDVALUE(fct_transfer_market_value_analysis[transfer_season], "Tum sezonlar") VAR PositionLabel = SELECTEDVALUE(fct_transfer_market_value_analysis[position], "Tum pozisyonlar") RETURN SeasonLabel & " | " & PositionLabel & " | " & FORMAT([Transfer Count], "#,0") & " transfer"
		displayFolder: Market Value Analysis\05 Dynamic Context

	column transfer_key
		dataType: string
		summarizeBy: none
		sourceColumn: transfer_key

		annotation SummarizationSetBy = Automatic

	column player_id
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: player_id

		annotation SummarizationSetBy = Automatic

	column player_name
		dataType: string
		summarizeBy: none
		sourceColumn: player_name

		annotation SummarizationSetBy = Automatic

	column position
		dataType: string
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column sub_position
		dataType: string
		summarizeBy: none
		sourceColumn: sub_position

		annotation SummarizationSetBy = Automatic

	column birth_date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: birth_date

		variation Variation
			isDefault
			relationship: 54592705-61b1-4989-9614-24453e8f03b1
			defaultHierarchy: LocalDateTable_ee0c45f5-5ce6-412a-b743-c5e9780a29a6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column country_of_citizenship
		dataType: string
		summarizeBy: none
		sourceColumn: country_of_citizenship

		annotation SummarizationSetBy = Automatic

	column age_at_transfer
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: age_at_transfer

		annotation SummarizationSetBy = Automatic

	column transfer_date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: transfer_date

		variation Variation
			isDefault
			relationship: edad52db-35ab-4cc1-bac7-3b6b4a3ac969
			defaultHierarchy: LocalDateTable_402390ed-838f-413f-8b34-00e012dc29fa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column transfer_year
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: transfer_year

		annotation SummarizationSetBy = Automatic

	column transfer_month
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: transfer_month

		annotation SummarizationSetBy = Automatic

	column transfer_season
		dataType: string
		summarizeBy: none
		sourceColumn: transfer_season

		annotation SummarizationSetBy = Automatic

	column is_future_transfer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: is_future_transfer

		annotation SummarizationSetBy = Automatic

	column transfer_sequence_number
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: transfer_sequence_number

		annotation SummarizationSetBy = Automatic

	column player_transfer_count
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: player_transfer_count

		annotation SummarizationSetBy = Automatic

	column known_fee_transfer_count
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: known_fee_transfer_count

		annotation SummarizationSetBy = Automatic

	column is_latest_transfer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: is_latest_transfer

		annotation SummarizationSetBy = Automatic

	column previous_transfer_date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: previous_transfer_date

		variation Variation
			isDefault
			relationship: 2de34f5f-a9d7-49b8-89f7-afb75293ff40
			defaultHierarchy: LocalDateTable_1665a1cb-5e3c-4d65-9651-6326caba3068.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column days_since_previous_transfer
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: days_since_previous_transfer

		annotation SummarizationSetBy = Automatic

	column next_transfer_date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: next_transfer_date

		variation Variation
			isDefault
			relationship: de28e0ad-71e4-40a5-9420-39e9b91a7920
			defaultHierarchy: LocalDateTable_48709e1d-bf47-47cc-94d5-7511b4ad5222.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column days_to_next_transfer
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: days_to_next_transfer

		annotation SummarizationSetBy = Automatic

	column from_club_id
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: from_club_id

		annotation SummarizationSetBy = Automatic

	column from_club_name
		dataType: string
		summarizeBy: none
		sourceColumn: from_club_name

		annotation SummarizationSetBy = Automatic

	column to_club_id
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: to_club_id

		annotation SummarizationSetBy = Automatic

	column to_club_name
		dataType: string
		summarizeBy: none
		sourceColumn: to_club_name

		annotation SummarizationSetBy = Automatic

	column transfer_fee
		dataType: double
		summarizeBy: sum
		sourceColumn: transfer_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cumulative_known_transfer_fee
		dataType: double
		summarizeBy: sum
		sourceColumn: cumulative_known_transfer_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_transfer_fee
		dataType: double
		summarizeBy: sum
		sourceColumn: total_transfer_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column avg_transfer_fee
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_transfer_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column max_transfer_fee
		dataType: double
		summarizeBy: sum
		sourceColumn: max_transfer_fee

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fee_status
		dataType: string
		summarizeBy: none
		sourceColumn: fee_status

		annotation SummarizationSetBy = Automatic

	column has_known_transfer_fee
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: has_known_transfer_fee

		annotation SummarizationSetBy = Automatic

	column transfer_record_market_value
		dataType: double
		summarizeBy: sum
		sourceColumn: transfer_record_market_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column has_transfer_record_market_value
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: has_transfer_record_market_value

		annotation SummarizationSetBy = Automatic

	column market_value_baseline_date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: market_value_baseline_date

		variation Variation
			isDefault
			relationship: 88ee5f87-a47b-4fc6-936a-b4b62473d503
			defaultHierarchy: LocalDateTable_17e963b7-e819-4176-97e6-c3277aa03c52.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column market_value_baseline
		dataType: double
		summarizeBy: sum
		sourceColumn: market_value_baseline

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column market_value_baseline_source
		dataType: string
		summarizeBy: none
		sourceColumn: market_value_baseline_source

		annotation SummarizationSetBy = Automatic

	column has_market_value_baseline
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: has_market_value_baseline

		annotation SummarizationSetBy = Automatic

	column has_fee_market_value_comparison
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: has_fee_market_value_comparison

		annotation SummarizationSetBy = Automatic

	column days_since_market_value_baseline
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: days_since_market_value_baseline

		annotation SummarizationSetBy = Automatic

	column fee_market_value_difference
		dataType: double
		summarizeBy: sum
		sourceColumn: fee_market_value_difference

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fee_market_value_difference_pct
		dataType: double
		summarizeBy: sum
		sourceColumn: fee_market_value_difference_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column fee_to_market_value_ratio
		dataType: double
		summarizeBy: sum
		sourceColumn: fee_to_market_value_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prior_valuation_date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: prior_valuation_date

		variation Variation
			isDefault
			relationship: 9b01f1c4-f1f8-4867-b55e-8d2e5aa30f61
			defaultHierarchy: LocalDateTable_08a49516-31cd-48b4-89ba-dc2db016d8cf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column prior_market_value
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: prior_market_value

		annotation SummarizationSetBy = Automatic

	column prior_valuation_club_id
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: prior_valuation_club_id

		annotation SummarizationSetBy = Automatic

	column prior_valuation_club_name
		dataType: string
		summarizeBy: none
		sourceColumn: prior_valuation_club_name

		annotation SummarizationSetBy = Automatic

	column prior_valuation_competition_id
		dataType: string
		summarizeBy: none
		sourceColumn: prior_valuation_competition_id

		annotation SummarizationSetBy = Automatic

	column prior_competition_name
		dataType: string
		summarizeBy: none
		sourceColumn: prior_competition_name

		annotation SummarizationSetBy = Automatic

	column prior_competition_country_name
		dataType: string
		summarizeBy: none
		sourceColumn: prior_competition_country_name

		annotation SummarizationSetBy = Automatic

	column prior_competition_confederation
		dataType: string
		summarizeBy: none
		sourceColumn: prior_competition_confederation

		annotation SummarizationSetBy = Automatic

	column has_prior_valuation
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: has_prior_valuation

		annotation SummarizationSetBy = Automatic

	column days_since_prior_valuation
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: days_since_prior_valuation

		annotation SummarizationSetBy = Automatic

	column next_valuation_date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: next_valuation_date

		variation Variation
			isDefault
			relationship: 8f773ac8-a682-4482-bac5-0edd297dcbe2
			defaultHierarchy: LocalDateTable_2dd0becb-a826-4faa-adbd-8dbd411a199d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column next_market_value
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: next_market_value

		annotation SummarizationSetBy = Automatic

	column next_valuation_club_id
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: next_valuation_club_id

		annotation SummarizationSetBy = Automatic

	column next_valuation_club_name
		dataType: string
		summarizeBy: none
		sourceColumn: next_valuation_club_name

		annotation SummarizationSetBy = Automatic

	column next_valuation_competition_id
		dataType: string
		summarizeBy: none
		sourceColumn: next_valuation_competition_id

		annotation SummarizationSetBy = Automatic

	column next_competition_name
		dataType: string
		summarizeBy: none
		sourceColumn: next_competition_name

		annotation SummarizationSetBy = Automatic

	column next_competition_country_name
		dataType: string
		summarizeBy: none
		sourceColumn: next_competition_country_name

		annotation SummarizationSetBy = Automatic

	column next_competition_confederation
		dataType: string
		summarizeBy: none
		sourceColumn: next_competition_confederation

		annotation SummarizationSetBy = Automatic

	column has_next_valuation
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: has_next_valuation

		annotation SummarizationSetBy = Automatic

	column days_to_next_valuation
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: days_to_next_valuation

		annotation SummarizationSetBy = Automatic

	column market_value_change_after_transfer
		dataType: double
		summarizeBy: sum
		sourceColumn: market_value_change_after_transfer

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column market_value_change_after_transfer_pct
		dataType: double
		summarizeBy: sum
		sourceColumn: market_value_change_after_transfer_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column has_post_transfer_value_change
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: has_post_transfer_value_change

		annotation SummarizationSetBy = Automatic

	column market_value_direction_after_transfer
		dataType: string
		summarizeBy: none
		sourceColumn: market_value_direction_after_transfer

		annotation SummarizationSetBy = Automatic

	column valuation_context_change
		dataType: string
		summarizeBy: none
		sourceColumn: valuation_context_change

		annotation SummarizationSetBy = Automatic

	column first_valuation_date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: first_valuation_date

		variation Variation
			isDefault
			relationship: 65e79f51-5217-4e34-8840-ed34620c5c11
			defaultHierarchy: LocalDateTable_d105d730-64ba-4e7d-8133-fcecdbcb7bfc.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column latest_valuation_date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: latest_valuation_date

		variation Variation
			isDefault
			relationship: 5b64f022-0d68-48e3-8711-115d0c7617e4
			defaultHierarchy: LocalDateTable_6ae1fcc1-20a1-4422-b9b3-8e685bffd029.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column first_market_value
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: first_market_value

		annotation SummarizationSetBy = Automatic

	column current_market_value
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: current_market_value

		annotation SummarizationSetBy = Automatic

	column highest_market_value
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: highest_market_value

		annotation SummarizationSetBy = Automatic

	column career_market_value_growth
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: career_market_value_growth

		annotation SummarizationSetBy = Automatic

	column career_market_value_growth_pct
		dataType: double
		summarizeBy: sum
		sourceColumn: career_market_value_growth_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column yon_etiketi_tr
		dataType: string
		summarizeBy: none
		sourceColumn: yon_etiketi_tr

		annotation SummarizationSetBy = Automatic

	column pozisyon_tr
		dataType: string
		summarizeBy: none
		sourceColumn: pozisyon_tr

		annotation SummarizationSetBy = Automatic

	partition fct_transfer_market_value_analysis = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database(),
				    #"data-analiz-490513" = Source{[Name="data-analiz-490513"]}[Data],
				    football_mart_Schema = #"data-analiz-490513"{[Name="football_mart",Kind="Schema"]}[Data],
				    fct_transfer_market_value_analysis_Table = football_mart_Schema{[Name="fct_transfer_market_value_analysis",Kind="Table"]}[Data]
				in
				    fct_transfer_market_value_analysis_Table

