table fct_player_performance

	measure 'Toplam Gol' = SUM(fct_player_performance[total_goals])
		formatString: 0

	measure 'Toplam Asist' = SUM(fct_player_performance[total_assists])
		formatString: 0

	measure 'Toplam Dakika' = SUM(fct_player_performance[total_minutes_played])
		formatString: 0

	measure 'Toplam Oyuncu' = DISTINCTCOUNT(fct_player_performance[player_id])
		formatString: 0

	measure 'Player G+A per 90' = MAX(fct_player_performance[goals_per_90]) + MAX(fct_player_performance[assists_per_90])

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg G+A per 90' =

			AVERAGEX(
			    fct_player_performance,
			    fct_player_performance[goals_per_90] + fct_player_performance[assists_per_90]
			)

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ortalama Dakika' =
			
			AVERAGE(fct_player_performance[avg_minutes_per_match])

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column player_id
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: player_id

		annotation SummarizationSetBy = Automatic

	column player_name
		dataType: string
		summarizeBy: none
		sourceColumn: player_name

		annotation SummarizationSetBy = Automatic

	column position
		dataType: string
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column sub_position
		dataType: string
		summarizeBy: none
		sourceColumn: sub_position

		annotation SummarizationSetBy = Automatic

	column current_club_id
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: current_club_id

		annotation SummarizationSetBy = Automatic

	column current_club_name
		dataType: string
		summarizeBy: none
		sourceColumn: current_club_name

		annotation SummarizationSetBy = Automatic

	column market_value_in_eur
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: market_value_in_eur

		annotation SummarizationSetBy = Automatic

	column has_current_market_value
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: has_current_market_value

		annotation SummarizationSetBy = Automatic

	column matches_played
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: matches_played

		annotation SummarizationSetBy = Automatic

	column total_goals
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: total_goals

		annotation SummarizationSetBy = Automatic

	column total_assists
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: total_assists

		annotation SummarizationSetBy = Automatic

	column total_minutes_played
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: total_minutes_played

		annotation SummarizationSetBy = Automatic

	column total_yellow_cards
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: total_yellow_cards

		annotation SummarizationSetBy = Automatic

	column total_red_cards
		dataType: int64
		formatString: 0
		summarizeBy: sum
		sourceColumn: total_red_cards

		annotation SummarizationSetBy = Automatic

	column avg_minutes_per_match
		dataType: double
		summarizeBy: sum
		sourceColumn: avg_minutes_per_match

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column goals_per_match
		dataType: double
		summarizeBy: sum
		sourceColumn: goals_per_match

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column assists_per_match
		dataType: double
		summarizeBy: sum
		sourceColumn: assists_per_match

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column goals_per_90
		dataType: double
		summarizeBy: sum
		sourceColumn: goals_per_90

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column assists_per_90
		dataType: double
		summarizeBy: sum
		sourceColumn: assists_per_90

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition fct_player_performance = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database([UseStorageApi=false]),
				    #"data-analiz-490513" = Source{[Name="data-analiz-490513"]}[Data],
				    football_mart_Schema = #"data-analiz-490513"{[Name="football_mart",Kind="Schema"]}[Data],
				    fct_player_performance_Table = football_mart_Schema{[Name="fct_player_performance",Kind="Table"]}[Data]
				in
				    fct_player_performance_Table

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

