table ml_player_market_value_current_predictions
	lineageTag: 94b4b496-94a5-4bd8-bab7-11720e0f3737

	/// Distinct players with a current market-value prediction.
	measure 'Scored Player Count' = DISTINCTCOUNT(ml_player_market_value_current_predictions[player_id])
		formatString: #,0 "oyuncu"
		displayFolder: Market Value Prediction\01 Scope
		lineageTag: 9ddecb5a-d7f5-4c56-bfe3-0b14b7e534d4

	/// Players with high or medium prediction quality.
	measure 'Decision Ready Player Count' = CALCULATE([Scored Player Count], ml_player_market_value_current_predictions[prediction_quality_status] IN {"high", "medium"})
		formatString: #,0 "oyuncu"
		displayFolder: Market Value Prediction\02 Trust
		lineageTag: 2a06cb71-8762-41e0-8056-94b4c3c780b5

	/// Share of scored players suitable for decision support.
	measure 'Decision Ready Rate %' = COALESCE(DIVIDE([Decision Ready Player Count], [Scored Player Count]), 0)
		formatString: 0.0%
		displayFolder: Market Value Prediction\02 Trust
		lineageTag: 6d21486a-41ff-41e4-99f3-644763bb2858

	/// Average current predicted market value.
	measure 'Average Predicted Market Value' = AVERAGE(ml_player_market_value_current_predictions[predicted_market_value_eur])
		formatString: €0.0
		displayFolder: Market Value Prediction\03 Valuation
		lineageTag: eabc5db3-eae6-45ae-bc68-3d02d40d3065

	/// Average previous observed market value.
	measure 'Average Previous Market Value' = AVERAGE(ml_player_market_value_current_predictions[previous_market_value_eur])
		formatString: €0.0
		displayFolder: Market Value Prediction\03 Valuation
		lineageTag: 8b7d8f12-4c39-475b-91e0-8377297c53ab

	/// Average predicted percentage change versus previous market value.
	measure 'Average Prediction Upside %' = DIVIDE(AVERAGE(ml_player_market_value_current_predictions[prediction_delta_vs_previous_pct]), 100)
		formatString: 0.0%
		displayFolder: Market Value Prediction\04 Opportunity
		lineageTag: 76db9d4e-b54e-46e5-b33f-6a07f5aaf18f

	/// Players with positive predicted upside versus previous market value.
	measure 'Positive Upside Player Count' = CALCULATE([Scored Player Count], ml_player_market_value_current_predictions[prediction_delta_vs_previous_pct] > 0)
		formatString: #,0 "oyuncu"
		displayFolder: Market Value Prediction\04 Opportunity
		lineageTag: 61c138bd-9519-42c7-8a07-3aa57ab5c475

	/// Share of scored players with positive predicted upside.
	measure 'Positive Upside Rate %' = COALESCE(DIVIDE([Positive Upside Player Count], [Scored Player Count]), 0)
		formatString: 0.0%
		displayFolder: Market Value Prediction\04 Opportunity
		lineageTag: 9b566556-9ad5-4a2c-89bf-60bff2c8b02d

	/// Average prediction interval width.
	measure 'Average Prediction Interval' = AVERAGE(ml_player_market_value_current_predictions[prediction_interval_eur])
		formatString: €0.0
		displayFolder: Market Value Prediction\02 Trust
		lineageTag: a132d2a7-ca56-40cf-9990-80cc0af6a4f9

	/// Average prediction interval relative to predicted market value.
	measure 'Average Relative Prediction Interval %' = DIVIDE([Average Prediction Interval], [Average Predicted Market Value])
		formatString: 0.0%
		displayFolder: Market Value Prediction\02 Trust
		lineageTag: bf0631ad-9ffc-4dd4-8fc0-6a5d67430443

	/// Selected player label for drill-through pages.
	measure 'Selected Prediction Player' = SELECTEDVALUE(ml_player_market_value_current_predictions[player_name], "Oyuncu secilmedi")
		displayFolder: Market Value Prediction\05 Dynamic Context
		lineageTag: 3ba0aac0-5f5b-4c04-9f93-5fb7d030df83

	/// Dynamic prediction context summary driven by active filters.
	measure 'Prediction Context Summary' = VAR PositionLabel = SELECTEDVALUE(ml_player_market_value_current_predictions[pozisyon_tr], "Tüm Pozisyonlar") VAR CountryLabel = SELECTEDVALUE(ml_player_market_value_current_predictions[competition_country_name], "Tüm Ülkeler") RETURN PositionLabel & " | " & CountryLabel & " | " & FORMAT([Scored Player Count], "#,0") & " oyuncu"
		displayFolder: Market Value Prediction\05 Dynamic Context
		lineageTag: b294791c-4b63-4113-97c4-3dde99a3efec

	/// Dynamic page title driven by active slicer selections.
	measure 'ML Page Dynamic Title' = VAR p = SELECTEDVALUE(ml_player_market_value_current_predictions[pozisyon_tr], "Tüm Pozisyonlar") VAR c = SELECTEDVALUE(ml_player_market_value_current_predictions[competition_country_name], "Tüm Ülkeler") RETURN "⭐ Piyasa Değeri Tahmini  │  " & p & "  │  " & c
		displayFolder: Market Value Prediction\05 Dynamic Context
		lineageTag: 6e3a34ae-8a3e-4d4c-af3e-cf79a607cebf

	/// Players with predicted upside greater than 20% — high-opportunity targets.
	measure 'Büyük Artış Oyuncu Count' = CALCULATE([Scored Player Count], ml_player_market_value_current_predictions[prediction_delta_vs_previous_pct] > 20)
		formatString: #,0 "oyuncu"
		displayFolder: Market Value Prediction\04 Opportunity
		lineageTag: 679dff1f-43e0-47e7-9eaf-6b2e3d66d02b

	/// Inverse of average relative interval — higher means more confident predictions.
	measure 'Average Prediction Confidence %' = 1 - [Average Relative Prediction Interval %]
		formatString: 0.0%
		displayFolder: Market Value Prediction\02 Trust
		lineageTag: eec0a1d9-6f9c-4ce8-ba79-23bb079a5921

	/// Decision-ready players with positive upside — actionable long list.
	measure 'High Upside Decision Ready Count' = CALCULATE([Decision Ready Player Count], ml_player_market_value_current_predictions[prediction_delta_vs_previous_pct] > 0)
		formatString: #,0 "oyuncu"
		displayFolder: Market Value Prediction\04 Opportunity
		lineageTag: ea860a65-245a-4505-bfce-1eed4a4bf4bd

	column scoring_row_key
		dataType: string
		lineageTag: 7fbc1f5f-3048-4adc-af85-ced31846e2ec
		summarizeBy: none
		sourceColumn: scoring_row_key

		annotation SummarizationSetBy = Automatic

	column player_id
		dataType: int64
		formatString: 0
		lineageTag: bb10f3f1-e12d-4447-a3e3-13b5c818a8fb
		summarizeBy: none
		sourceColumn: player_id

		annotation SummarizationSetBy = Automatic

	column player_name
		dataType: string
		lineageTag: c1a7d5b0-7942-4e45-b5ef-9eca8cad6380
		summarizeBy: none
		sourceColumn: player_name

		annotation SummarizationSetBy = Automatic

	column prediction_as_of_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1bbc19dc-49f7-4d3a-8c9a-f0ad677b236b
		summarizeBy: none
		sourceColumn: prediction_as_of_date

		variation Variation
			isDefault
			relationship: 9e57c1db-d822-46c3-81e8-824de18519c3
			defaultHierarchy: LocalDateTable_b8320c0b-7c0a-405e-855b-4099d40c196f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column season
		dataType: double
		lineageTag: 3e5961af-23b0-4930-9154-27879a9ee65a
		summarizeBy: sum
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column height_in_cm
		dataType: double
		lineageTag: dc327114-d1a9-466b-aa9a-fff99783cb08
		summarizeBy: sum
		sourceColumn: height_in_cm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column age_at_target_date
		dataType: double
		lineageTag: b895d37d-53d7-4afa-8f5a-bc2cecfb54bb
		summarizeBy: sum
		sourceColumn: age_at_target_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column matches_before_target
		dataType: double
		lineageTag: 1ce0515c-0949-480f-91fe-ff94ee1c51e5
		summarizeBy: sum
		sourceColumn: matches_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column competitions_played_before_target
		dataType: double
		lineageTag: 1149602b-69ab-4c7c-bc7b-0d203666320f
		summarizeBy: sum
		sourceColumn: competitions_played_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column minutes_before_target
		dataType: double
		lineageTag: 2ba24bff-524e-4292-88b0-ac5ffb6ecf8c
		summarizeBy: sum
		sourceColumn: minutes_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column goals_before_target
		dataType: double
		lineageTag: f2a9f5aa-bb08-4d4f-bfda-d541fb8cf160
		summarizeBy: sum
		sourceColumn: goals_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column assists_before_target
		dataType: double
		lineageTag: 4cd03d3c-c1d6-428c-9f08-7bc6d67d06da
		summarizeBy: sum
		sourceColumn: assists_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column yellow_cards_before_target
		dataType: double
		lineageTag: 72da5fbe-2a4c-4d00-9e00-fba2f4ee89f3
		summarizeBy: sum
		sourceColumn: yellow_cards_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column red_cards_before_target
		dataType: double
		lineageTag: 458f6c8a-0a28-44a0-af2b-f3dc1227aa97
		summarizeBy: sum
		sourceColumn: red_cards_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column goals_per_90_before_target
		dataType: double
		lineageTag: 8cc2fb7a-f28e-487f-923e-7107e57ddf6c
		summarizeBy: sum
		sourceColumn: goals_per_90_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column assists_per_90_before_target
		dataType: double
		lineageTag: 2dbe78fb-b7e6-4464-952a-8440902c8e36
		summarizeBy: sum
		sourceColumn: assists_per_90_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column previous_market_value_eur
		dataType: double
		lineageTag: 7909810d-b72d-4f88-8624-a087f0f48b41
		summarizeBy: sum
		sourceColumn: previous_market_value_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column days_since_previous_market_value
		dataType: double
		lineageTag: 87ae19b3-27d8-4c40-aade-4c55eb31c277
		summarizeBy: sum
		sourceColumn: days_since_previous_market_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prior_valuation_count
		dataType: double
		lineageTag: f8021acc-500b-467a-ab6a-ae6d913604d5
		summarizeBy: sum
		sourceColumn: prior_valuation_count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prior_highest_market_value_eur
		dataType: double
		lineageTag: f7ecc48b-8dc8-4cc1-85a4-ac8df55a8207
		summarizeBy: sum
		sourceColumn: prior_highest_market_value_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column position
		dataType: string
		lineageTag: 4657bc5c-9a8c-48fd-97f6-feea2391656d
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column sub_position
		dataType: string
		lineageTag: 7741f867-b6fb-4ee3-b369-5c1a84a1a7bc
		summarizeBy: none
		sourceColumn: sub_position

		annotation SummarizationSetBy = Automatic

	column preferred_foot
		dataType: string
		lineageTag: d24116eb-1984-4308-8f47-c91c8b2be4a0
		summarizeBy: none
		sourceColumn: preferred_foot

		annotation SummarizationSetBy = Automatic

	column country_of_citizenship
		dataType: string
		lineageTag: f0c3a197-a6c6-4b38-9a89-41c576778c81
		summarizeBy: none
		sourceColumn: country_of_citizenship

		annotation SummarizationSetBy = Automatic

	column competition_id
		dataType: string
		lineageTag: 30d85724-ea9c-47d3-b12e-37dea6786e9e
		summarizeBy: none
		sourceColumn: competition_id

		annotation SummarizationSetBy = Automatic

	column competition_type
		dataType: string
		lineageTag: f3d32636-f6ea-47b6-a5c7-3280e53f318a
		summarizeBy: none
		sourceColumn: competition_type

		annotation SummarizationSetBy = Automatic

	column competition_country_name
		dataType: string
		lineageTag: d0714972-f7a3-418e-9686-87ce7a65ef96
		summarizeBy: none
		sourceColumn: competition_country_name

		annotation SummarizationSetBy = Automatic

	column confederation
		dataType: string
		lineageTag: 9eebcc81-2db3-47d1-9b92-5a3deb13b9b7
		summarizeBy: none
		sourceColumn: confederation

		annotation SummarizationSetBy = Automatic

	column ml_only_prediction_eur
		dataType: double
		lineageTag: 772d8aff-c1c7-4784-98b0-cd2fef3f07ca
		summarizeBy: sum
		sourceColumn: ml_only_prediction_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column baseline_prediction_eur
		dataType: double
		lineageTag: f2a16fc3-c19f-4005-a46a-044094d46e91
		summarizeBy: sum
		sourceColumn: baseline_prediction_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column predicted_market_value_eur
		dataType: double
		lineageTag: 5cc31db1-0dea-43e3-8679-17b796cc8f36
		summarizeBy: sum
		sourceColumn: predicted_market_value_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_interval_band
		dataType: string
		lineageTag: 67ecdc7b-3e99-4881-921a-7932007bd146
		summarizeBy: none
		sourceColumn: prediction_interval_band

		annotation SummarizationSetBy = Automatic

	column prediction_interval_eur
		dataType: double
		lineageTag: e9aae04d-221f-44b7-b99b-bb55720cc565
		summarizeBy: sum
		sourceColumn: prediction_interval_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_lower_eur
		dataType: double
		lineageTag: c8926807-e4bb-4cb7-83dc-d6401dab5c14
		summarizeBy: sum
		sourceColumn: prediction_lower_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_upper_eur
		dataType: double
		lineageTag: 198f094a-f7ba-4463-9fc8-4ccf81330e11
		summarizeBy: sum
		sourceColumn: prediction_upper_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_delta_vs_previous_eur
		dataType: double
		lineageTag: 9d71febb-7c5a-4b72-9f3c-210e385d1d9d
		summarizeBy: sum
		sourceColumn: prediction_delta_vs_previous_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_delta_vs_previous_pct
		dataType: double
		lineageTag: bed2109e-0b1a-4334-a498-e65a7870d95c
		summarizeBy: sum
		sourceColumn: prediction_delta_vs_previous_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_quality_status
		dataType: string
		lineageTag: 28d3e450-af38-4972-aeb8-4f63c998b713
		summarizeBy: none
		sourceColumn: prediction_quality_status

		annotation SummarizationSetBy = Automatic

	column prediction_is_out_of_time
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1cb1d6f4-dde9-4ef1-9c81-def6e84bc82e
		summarizeBy: none
		sourceColumn: prediction_is_out_of_time

		annotation SummarizationSetBy = Automatic

	column selected_ml_blend_weight
		dataType: double
		lineageTag: 7f52b3eb-f5eb-417c-8045-6ac8473d1322
		summarizeBy: sum
		sourceColumn: selected_ml_blend_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column model_version
		dataType: string
		lineageTag: 3138a51b-3822-44b6-b760-e3a1023c5d25
		summarizeBy: none
		sourceColumn: model_version

		annotation SummarizationSetBy = Automatic

	column model_generated_at_utc
		dataType: dateTime
		formatString: General Date
		lineageTag: 6f574aeb-ee07-4a2b-a819-b222f5421811
		summarizeBy: none
		sourceColumn: model_generated_at_utc

		variation Variation
			isDefault
			relationship: 9b8c44b4-93b9-4108-a3ff-4f8ebac5e9ac
			defaultHierarchy: LocalDateTable_ad25d67e-0f83-42c8-8ecc-07ea59db5e35.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column pozisyon_tr
		dataType: string
		lineageTag: 0d275db6-cb2b-476e-b887-4b639a9354ed
		summarizeBy: none
		sourceColumn: pozisyon_tr

		annotation SummarizationSetBy = Automatic

	column kalite_etiketi_tr
		dataType: string
		lineageTag: e2065328-12fa-4d3b-b643-60c153313c6f
		summarizeBy: none
		sourceColumn: kalite_etiketi_tr

		annotation SummarizationSetBy = Automatic

	partition ml_player_market_value_current_predictions = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database([UseStorageApi=false]),
				    #"data-analiz-490513" = Source{[Name="data-analiz-490513"]}[Data],
				    football_ml_Schema = #"data-analiz-490513"{[Name="football_ml",Kind="Schema"]}[Data],
				    ml_player_market_value_current_predictions_Table = football_ml_Schema{[Name="ml_player_market_value_current_predictions",Kind="Table"]}[Data]
				in
				    ml_player_market_value_current_predictions_Table

