table ml_player_market_value_current_predictions

	/// Distinct players with a current market-value prediction.
	measure 'Scored Player Count' = DISTINCTCOUNT(ml_player_market_value_current_predictions[player_id])
		formatString: #,0 "oyuncu"
		displayFolder: Market Value Prediction\01 Scope

	/// Players with high or medium prediction quality.
	measure 'Decision Ready Player Count' = CALCULATE([Scored Player Count], ml_player_market_value_current_predictions[prediction_quality_status] IN {"high", "medium"})
		formatString: #,0 "oyuncu"
		displayFolder: Market Value Prediction\02 Trust

	/// Share of scored players suitable for decision support.
	measure 'Decision Ready Rate %' = COALESCE(DIVIDE([Decision Ready Player Count], [Scored Player Count]), 0)
		formatString: 0.0%
		displayFolder: Market Value Prediction\02 Trust

	/// Average current predicted market value.
	measure 'Average Predicted Market Value' = AVERAGE(ml_player_market_value_current_predictions[predicted_market_value_eur])
		formatString: €0.0
		displayFolder: Market Value Prediction\03 Valuation

	/// Average previous observed market value.
	measure 'Average Previous Market Value' = AVERAGE(ml_player_market_value_current_predictions[previous_market_value_eur])
		formatString: €0.0
		displayFolder: Market Value Prediction\03 Valuation

	/// Average predicted percentage change versus previous market value.
	measure 'Average Prediction Upside %' = DIVIDE(AVERAGE(ml_player_market_value_current_predictions[prediction_delta_vs_previous_pct]), 100)
		formatString: 0.0%
		displayFolder: Market Value Prediction\04 Opportunity

	/// Players with positive predicted upside versus previous market value.
	measure 'Positive Upside Player Count' = CALCULATE([Scored Player Count], ml_player_market_value_current_predictions[prediction_delta_vs_previous_pct] > 0)
		formatString: #,0 "oyuncu"
		displayFolder: Market Value Prediction\04 Opportunity

	/// Share of scored players with positive predicted upside.
	measure 'Positive Upside Rate %' = COALESCE(DIVIDE([Positive Upside Player Count], [Scored Player Count]), 0)
		formatString: 0.0%
		displayFolder: Market Value Prediction\04 Opportunity

	/// Average prediction interval width.
	measure 'Average Prediction Interval' = AVERAGE(ml_player_market_value_current_predictions[prediction_interval_eur])
		formatString: €0.0
		displayFolder: Market Value Prediction\02 Trust

	/// Average prediction interval relative to predicted market value.
	measure 'Average Relative Prediction Interval %' = DIVIDE([Average Prediction Interval], [Average Predicted Market Value])
		formatString: 0.0%
		displayFolder: Market Value Prediction\02 Trust

	/// Selected player label for drill-through pages.
	measure 'Selected Prediction Player' = SELECTEDVALUE(ml_player_market_value_current_predictions[player_name], "Oyuncu secilmedi")
		displayFolder: Market Value Prediction\05 Dynamic Context

	/// Dynamic prediction context summary driven by active filters.
	measure 'Prediction Context Summary' = VAR PositionLabel = SELECTEDVALUE(ml_player_market_value_current_predictions[pozisyon_tr], "Tüm Pozisyonlar") VAR CountryLabel = SELECTEDVALUE(ml_player_market_value_current_predictions[competition_country_name], "Tüm Ülkeler") RETURN PositionLabel & " | " & CountryLabel & " | " & FORMAT([Scored Player Count], "#,0") & " oyuncu"
		displayFolder: Market Value Prediction\05 Dynamic Context

	/// Dynamic page title driven by active slicer selections.
	measure 'ML Page Dynamic Title' = VAR p = SELECTEDVALUE(ml_player_market_value_current_predictions[pozisyon_tr], "Tüm Pozisyonlar") VAR c = SELECTEDVALUE(ml_player_market_value_current_predictions[competition_country_name], "Tüm Ülkeler") RETURN "⭐ Piyasa Değeri Tahmini  │  " & p & "  │  " & c
		displayFolder: Market Value Prediction\05 Dynamic Context

	/// Players with predicted upside greater than 20% — high-opportunity targets.
	measure 'Büyük Artış Oyuncu Count' = CALCULATE([Scored Player Count], ml_player_market_value_current_predictions[prediction_delta_vs_previous_pct] > 20)
		formatString: #,0 "oyuncu"
		displayFolder: Market Value Prediction\04 Opportunity

	/// Inverse of average relative interval — higher means more confident predictions.
	measure 'Average Prediction Confidence %' = 1 - [Average Relative Prediction Interval %]
		formatString: 0.0%
		displayFolder: Market Value Prediction\02 Trust

	/// Decision-ready players with positive upside — actionable long list.
	measure 'High Upside Decision Ready Count' = CALCULATE([Decision Ready Player Count], ml_player_market_value_current_predictions[prediction_delta_vs_previous_pct] > 0)
		formatString: #,0 "oyuncu"
		displayFolder: Market Value Prediction\04 Opportunity

	column scoring_row_key
		dataType: string
		summarizeBy: none
		sourceColumn: scoring_row_key

		annotation SummarizationSetBy = Automatic

	column player_id
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: player_id

		annotation SummarizationSetBy = Automatic

	column player_name
		dataType: string
		summarizeBy: none
		sourceColumn: player_name

		annotation SummarizationSetBy = Automatic

	column prediction_as_of_date
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: prediction_as_of_date

		variation Variation
			isDefault
			relationship: 9e57c1db-d822-46c3-81e8-824de18519c3
			defaultHierarchy: LocalDateTable_b8320c0b-7c0a-405e-855b-4099d40c196f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column season
		dataType: double
		summarizeBy: sum
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column height_in_cm
		dataType: double
		summarizeBy: sum
		sourceColumn: height_in_cm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column age_at_target_date
		dataType: double
		summarizeBy: sum
		sourceColumn: age_at_target_date

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column matches_before_target
		dataType: double
		summarizeBy: sum
		sourceColumn: matches_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column competitions_played_before_target
		dataType: double
		summarizeBy: sum
		sourceColumn: competitions_played_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column minutes_before_target
		dataType: double
		summarizeBy: sum
		sourceColumn: minutes_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column goals_before_target
		dataType: double
		summarizeBy: sum
		sourceColumn: goals_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column assists_before_target
		dataType: double
		summarizeBy: sum
		sourceColumn: assists_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column yellow_cards_before_target
		dataType: double
		summarizeBy: sum
		sourceColumn: yellow_cards_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column red_cards_before_target
		dataType: double
		summarizeBy: sum
		sourceColumn: red_cards_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column goals_per_90_before_target
		dataType: double
		summarizeBy: sum
		sourceColumn: goals_per_90_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column assists_per_90_before_target
		dataType: double
		summarizeBy: sum
		sourceColumn: assists_per_90_before_target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column previous_market_value_eur
		dataType: double
		summarizeBy: sum
		sourceColumn: previous_market_value_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column days_since_previous_market_value
		dataType: double
		summarizeBy: sum
		sourceColumn: days_since_previous_market_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prior_valuation_count
		dataType: double
		summarizeBy: sum
		sourceColumn: prior_valuation_count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prior_highest_market_value_eur
		dataType: double
		summarizeBy: sum
		sourceColumn: prior_highest_market_value_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column position
		dataType: string
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column sub_position
		dataType: string
		summarizeBy: none
		sourceColumn: sub_position

		annotation SummarizationSetBy = Automatic

	column preferred_foot
		dataType: string
		summarizeBy: none
		sourceColumn: preferred_foot

		annotation SummarizationSetBy = Automatic

	column country_of_citizenship
		dataType: string
		summarizeBy: none
		sourceColumn: country_of_citizenship

		annotation SummarizationSetBy = Automatic

	column competition_id
		dataType: string
		summarizeBy: none
		sourceColumn: competition_id

		annotation SummarizationSetBy = Automatic

	column competition_type
		dataType: string
		summarizeBy: none
		sourceColumn: competition_type

		annotation SummarizationSetBy = Automatic

	column competition_country_name
		dataType: string
		summarizeBy: none
		sourceColumn: competition_country_name

		annotation SummarizationSetBy = Automatic

	column confederation
		dataType: string
		summarizeBy: none
		sourceColumn: confederation

		annotation SummarizationSetBy = Automatic

	column ml_only_prediction_eur
		dataType: double
		summarizeBy: sum
		sourceColumn: ml_only_prediction_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column baseline_prediction_eur
		dataType: double
		summarizeBy: sum
		sourceColumn: baseline_prediction_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column predicted_market_value_eur
		dataType: double
		summarizeBy: sum
		sourceColumn: predicted_market_value_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_interval_band
		dataType: string
		summarizeBy: none
		sourceColumn: prediction_interval_band

		annotation SummarizationSetBy = Automatic

	column prediction_interval_eur
		dataType: double
		summarizeBy: sum
		sourceColumn: prediction_interval_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_lower_eur
		dataType: double
		summarizeBy: sum
		sourceColumn: prediction_lower_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_upper_eur
		dataType: double
		summarizeBy: sum
		sourceColumn: prediction_upper_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_delta_vs_previous_eur
		dataType: double
		summarizeBy: sum
		sourceColumn: prediction_delta_vs_previous_eur

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_delta_vs_previous_pct
		dataType: double
		summarizeBy: sum
		sourceColumn: prediction_delta_vs_previous_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column prediction_quality_status
		dataType: string
		summarizeBy: none
		sourceColumn: prediction_quality_status

		annotation SummarizationSetBy = Automatic

	column prediction_is_out_of_time
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		summarizeBy: none
		sourceColumn: prediction_is_out_of_time

		annotation SummarizationSetBy = Automatic

	column selected_ml_blend_weight
		dataType: double
		summarizeBy: sum
		sourceColumn: selected_ml_blend_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column model_version
		dataType: string
		summarizeBy: none
		sourceColumn: model_version

		annotation SummarizationSetBy = Automatic

	column model_generated_at_utc
		dataType: dateTime
		formatString: General Date
		summarizeBy: none
		sourceColumn: model_generated_at_utc

		variation Variation
			isDefault
			relationship: 9b8c44b4-93b9-4108-a3ff-4f8ebac5e9ac
			defaultHierarchy: LocalDateTable_ad25d67e-0f83-42c8-8ecc-07ea59db5e35.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column kalite_etiketi_tr = SWITCH([prediction_quality_status], "high", "Yüksek", "medium", "Orta", "limited", "Sınırlı", "Bilinmiyor")
		dataType: string
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column upside_kategori_tr = SWITCH(TRUE(), [prediction_delta_vs_previous_pct] > 20, "🟢 Büyük Artış (>%20)", [prediction_delta_vs_previous_pct] > 5, "🔵 Orta Artış (%5-20)", [prediction_delta_vs_previous_pct] > -5, "⚪ Stabil (±%5)", "🔴 Düşüş")
		dataType: string
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column age_group_tr = SWITCH(TRUE(), [age_at_target_date] < 21, "Genç (<21)", [age_at_target_date] < 26, "Yükselen (21-25)", [age_at_target_date] < 30, "Olgun (26-29)", "Tecrübeli (30+)")
		dataType: string
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition ml_player_market_value_current_predictions = m
		mode: import
		source =
				let
				    Source = GoogleBigQuery.Database([UseStorageApi=false]),
				    #"data-analiz-490513" = Source{[Name="data-analiz-490513"]}[Data],
				    football_ml_Schema = #"data-analiz-490513"{[Name="football_ml",Kind="Schema"]}[Data],
				    ml_player_market_value_current_predictions_Table = football_ml_Schema{[Name="ml_player_market_value_current_predictions",Kind="Table"]}[Data]
				in
				    ml_player_market_value_current_predictions_Table

